version: "3.8"

services:
  go:
    container_name: go
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    command: air
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local